services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./appdata:/app/data # Host makinedeki './appdata' dizinini container'daki '/app/data' dizinine bağla
    depends_on:
      - db
    environment:
    networks:
      - appnetwork

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "finman123*"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./init.sql:/scripts/init.sql
      - ./entrypoint.sh:/scripts/entrypoint.sh
      - mssql-data:/var/opt/mssql # MSSQL veritabanı verileri için bir named volume kullan
    command: /bin/bash /scripts/entrypoint.sh
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  mssql-data:
    driver: local
