services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./appdata:/app/data # Host makinedeki './appdata' dizinini container'daki '/app/data' dizinine bağla
    depends_on:
      - db
    networks:
      - appnetwork

  db:
    build: ./db
    ports:
      - 1433:1433
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge

volumes:
  mssql-data:
    driver: local
